# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-19 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barsystem_base', '0043_vendingmachineproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendingmachineproduct',
            name='virtual',
            field=models.BooleanField(default=False),
        ),
    ]
