# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-17 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barsystem', '0041_auto_20150802_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='value',
            field=models.CharField(max_length=64),
        ),
    ]
