# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barsystem', '0044_vendingmachineproduct_virtual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='special_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
