# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barsystem', '0045_auto_20170304_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
